import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

import { Main } from "@/components/layout/Main";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Dhagagia Social Welfare Society (DSWS)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("tracking-tight antialiased", lexend.className)}>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
